<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite ignored="2" hostname="LAPTOP-AD2BG20M" failures="0" tests="1" name="Default test" time="130.973" errors="0" timestamp="2021-07-19T15:59:31 IST">
  <testcase classname="com.Nm.Website.CartPage" name="carpagescenariotwo" time="122.756"/>
  <testcase classname="com.Nm.Website.CartPage" name="cartpagescenarioone" time="0.0">
    <ignored/>
  </testcase> <!-- cartpagescenarioone -->
  <testcase classname="com.Nm.Website.CartPage" name="carpagescenariothree" time="0.0">
    <ignored/>
  </testcase> <!-- carpagescenariothree -->
=======
<<<<<<< HEAD
<testsuite hostname="NMSLAP093" ignored="1" name="Default test" tests="1" failures="1" timestamp="16 Jul 2021 06:22:03 GMT" time="372.8" errors="0">
  <testcase name="netmedsfirstcustomer" time="345.96" classname="com.Nm.Website.NeetmedsFirst">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Starting at ?299] but found [Starting at ₹299]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Starting at ?299] but found [Starting at ₹299]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.Nm.Website.NeetmedsFirst.netmedsfirstcustomer(NeetmedsFirst.java:458)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- netmedsfirstcustomer -->
  <testcase name="NetmedsError" time="0.0" classname="com.Nm.Website.NeetmedsFirst">
    <ignored/>
  </testcase> <!-- NetmedsError -->
=======
<testsuite ignored="0" hostname="LAPTOP-AD2BG20M" failures="0" tests="1" name="Default test" time="249.34" errors="0" timestamp="2021-07-16T19:56:42 IST">
  <testcase classname="com.Nm.Website.CartPage" name="cartpage" time="241.092"/>
>>>>>>> 3d77564ae2e2c749e2f07b82f59fa9b765ffb09d
>>>>>>> 1b91610b5ad8dd3f5aec99340e5c677d547bc1a8
</testsuite> <!-- Default test -->
